### ISSUE TITLE
Selecting any of the HuBMAP IDs other than the first one (default) cause a Portal Erro

### ISSUE THREAD

**Issue by khanshawPSC** [hubmapconsortium/portal-ui#1737] opened 2021-04-16 19:32 UTC
On the Data Portal when using menu item Previews /
Cell Type Annotations
Selecting any of the HuBMAP IDs other than the first one (default) cause a Portal Error:

Error
URL: https://portal.hubmapconsortium.org/preview/cell-type-annotations

TypeError: null is not an object (evaluating 'n.find')

**Comment by mccalluc** [comment] 2021-04-16 20:07
Duplicate of #1731

**Closed by mccalluc** 2021-04-16 20:07 UTC
Labels: UI, bug
