### ISSUE TITLE
CCF EUI seems to just "spin" when "loading data"

### ISSUE THREAD

**Issue by debnigra** [hubmapconsortium/portal-ui#1432] opened 2020-12-21 14:42 UTC
User reports in ticket 1029:

> This link seems to load indefinitely.

> portal.hubmapconsortium.org/ccf-eui

> I confirmed on Safari and Chrome on Mac.

I can also confirm in Chrome on Windows.

**Comment by mccalluc** [comment] 2021-01-04 18:14
@debnigra : 
- Please use `triage` tag: I'm not watching all new issues in this repo.
- This is likely a duplicate of https://github.com/hubmapconsortium/ccf-ui/issues/296. Are you waiting significantly longer that 20s?

I'll move this issue to the CCF repo: Any fix would need to happen there.

**Closed** 2021-01-04 18:16 UTC
Labels: UI, bug
