### ISSUE TITLE
add page that lists version information for each service in the environment

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#889] opened 2020-07-24 22:48 UTC
Proposal for @mccalluc: can we add a (hidden) page that lists the versions of all services running in the current environment?

We had a discussion about how to communicate versions of services during the portal call on June 10th (https://docs.google.com/document/d/1ZXQ-tRYbnV1mRqFjaeaUxNPnh-6r6RkvHTzOTP3uk40/edit#heading=h.o682tmm73gfg):

```
Service version/commit hashes: We would like to be able to display the versions of the services that the portal UI relies on in the portal UI itself. This will be critical for meaningful error reporting.

ACTION ITEM: setup “info” endpoint returns json that has at least one required field “version”
```

This would require us to set up the page and to implement the `/info` endpoint for our service(s). Of course commitment to get this endpoint implemented for the other services is a prerequisite. At the time of the discussion, there was agreement that this could go forward.

**Comment by mccalluc** [comment] 2020-10-13 18:15
Duplicate of #1187. Closing.

**Closed by mccalluc** 2020-10-13 18:15 UTC
Labels: UI, proposal
