### ISSUE TITLE
Add "info" icon to areas requiring additional information

### ISSUE THREAD

**Issue by tsliaw** [hubmapconsortium/portal-ui#1076] opened 2020-08-19 15:45 UTC
Documentation for additional information text: https://docs.google.com/document/d/1iXVnd8ICkOJsdbhqJlrWh_KlxIgk3jMeY6Hb-jc0BMs/edit

**Comment by mccalluc** [comment] 2020-10-14 18:44
duplicate of #1182.

**Closed by mccalluc** 2020-10-14 18:44 UTC
Labels: UI, enhancement
