### ISSUE TITLE
adding datasets to a list does not work reliably on Safari

### ISSUE THREAD

**Issue by ngehlenborg** [hubmapconsortium/portal-ui#1587] opened 2021-02-25 20:44 UTC
I tried to add 5 datasets to a list by opening each in a separate tab (from the dataset browse page) and then hit "Save" and then "Edit Save Status" to assign them to a list that I had already created. Only the first dataset showed up in the list.

I also noticed issues with adding samples and donors to the "My Saved Items", which does seems to work reliably either. Again, I had multiple open tabs and added from separate tabs.

**Comment by ngehlenborg** [comment] 2021-02-26 14:13
I tried this again and didn't observe any issues when I used just a single tab for all operations in Safari.

**Comment by john-conroy** [comment] 2021-03-05 21:37
So you added a dataset from one tab and had the 'My Saved Items' open in another tab? Does refreshing show the dataset having been added?

**Comment by ngehlenborg** [comment] 2021-03-05 21:45
I think that is what I did. Refreshing didn't show the dataset being added.

**Comment by john-conroy** [comment] 2021-03-05 21:53
Hmm, I can't seem to reproduce it. I'll add it to the UI agenda.

**Comment by ngehlenborg** [comment] 2021-03-05 22:11
I will try to reproduce it, too.

**Comment by john-conroy** [comment] 2021-03-11 18:39
Per discussion in UI meeting, this was only observed in Safari's private mode. Safari's private mode does not share local storage across tabs, I assume this will be the case with IndexedDb as well, but that may not be true. Closing since this is private mode's intention.

**Closed by john-conroy** 2021-03-11 18:39 UTC
Labels: UI, bug, saved-lists
