### ISSUE TITLE
Dense feedback: Ajay

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#693] opened 2020-07-09 19:55 UTC
## Feedback

__Submitter Name__: Pillai, Ajay (NIH/NHGRI) [E] <ajay.pillai3@nih.gov>

__Submitter Email__:  Pillai, Ajay (NIH/NHGRI) [E] <ajay.pillai3@nih.gov>

__Message__:
After reading through this, I don't think I can parse it well enough into single items.  @ngehlenborg & @mccalluc - here's the full feedback from Ajay.  I will forward the email to Katy Borner as well in case the sizing / location stuff has to do w/ her.

Release Issue
Some top-level comments:
* I like the overall design, though it seems a bit muted. Not sure I am recommending anything specific here. 
* The front page (when you click on HuBMAP on the top row) counts and plots need to be fixed before release. 
* Currently there is no benefit in having three separate top-level links: Donor/Sample/Dataset. IF there is a plan to put up more detailed information about the donors (similarly for others) than what the columns currently contain. Otherwise it just looks like too many clicks bringing you to the same spot! 
* Does it make sense to wait to show donors/samples and just add more columns and only have datasets for the 1st release? BUT, if you have access to more metadata for the donors/samples currently i.e., can show more information in the tables then retain it. 
* It is unclear what collections means … I can guess … but it does not immediately make sense what I am supposed to do with it. Again, think about using a collection ID to filter datasets instead of an entirely separate link up top. 
* I think the showcases are nice, but need a LOT more in terms of description of what I am seeing and what a user could expect a few months from now with these. 
* CCF: Why is this not a showcase? 
* I cannot tell if it is functional currently. What exactly is it supposed to enable the user to accomplish right now? 
* I also cannot readily tell what I am supposed to do with it. After some patience, I notice that I can click on the individually highlighted parts of the organ. So I presume I might be able to visually extract out e.g., samples that are close to the main artery and samples that are far away from the main artery of the organ. Now, something like this might be useful, BUT I really can’t tell based on the lack of contrast which areas these might be. 
* The organs are NOT in the plane of the human. 
* The ontology terms search box does not seem to do anything specific. 
* It is unclear why clicking on some dataset on the right takes me to the sample page, and on others it takes me to some image and on yet others it goes nowhere. What is the image supposed to tell me? 
* The size of the organs are not relatively scaled (I know they are roughly the same size but it might make sense to scale the size of the spleen down a little bit, it’s about 20% smaller). 
* Is the tissue block size representative of its true size relative to the size of the organ? Clicking on the section of the tissue block, does change what is on the top … but it might be useful IF visually the change in the list on the right is enhanced in some manner by e.g., graying out or something. 
* It might be useful to consider using a table (like in the other parts) where I could do male/female selections of samples with or without ‘close-to/far-away-from main artery’. What other utility are you imagining currently of this?
---ajay 
PS: I expect to send a few more emails with more specific feedback.

**Comment by pecan88** [comment] 2020-07-09 20:15
Second set sent by Ajay.  I will extract and send to Bill & Phil the items that sound like they are API / Infrastructure related.

One more for Donors: I think you can convert BMI to an integer value … round it please.
help@hubmapconsortium.org changed status from closed to open
help@hubmapconsortium.org wrote: 
Building on previous email. 
Donors Tab: 
* Need more metadata in the tables that what is contained. 
* Does it make sense to sorting (in lieu of some filters)? 
* ID should be called Donor ID. 
* Group name can be abbreviated. 
* Why are there links to each entity which takes me to the same place … this is confusing and irritating (when I see a link I have some baseline expectation that I will get different/relevant information … please have only one link). 
* What is the interpretation of ‘last modified’? Why is this useful? 
* Clicking on an ID and then the protocols: does NOT take me to donor protocols aka any information about how the surgery or something like that was performed. This needs fixing. 
* Clicking on the donor: HBM737.MBKD.598 protocol takes me to a page that says ‘There is a newer version of protocols available’ this needs to be fixed. Though I like the protocol organization provided by Vanderbilt. The other groups need to be encouraged to have individual protocols like this one: https://www.protocols.io/view/vu-biomolecular-multimodal-imaging-center-biomic-k-bfskjncw 
* There needs to be some marker if the protocols change between two or more donors or it hasn’t. Otherwise the user is left to click on a complicated series of protocols to find out if there is any difference at all or not. 
* HBM528.WJLC.564 donor has no information in the protocols or any other details. This seems to be true for BOTH Caltech and Stanford samples. This is URGENT. 
* I am worried about the ‘Creator’ filter. It is unclear what it means. I also see people’s emails in Attribution. I think we need to be a bit careful about this. Do these people want their emails advertised? The contact PI is the only email contact we should retain. AND there should be multiple different types of attribution not just one name. 
* There is something wrong with the filter arithmetic … 
* Clicking on donors shows: 19 males, 16 females (I presume the rest of the 14 have no gender data). I also notice out of the 35, 27 are white and 8 black. 
* But, if I select females, I see 15 while and 1 black on the filters but the table shows no blacks. 
* I select males, I see 12 white and 7 black and the table shows 7 black (a table sorting function would be very useful to check these sort of things more readily). 
---ajay 
PS: More to follow …

**Comment by mccalluc** [comment] 2020-07-10 20:35
>     * I like the overall design, though it seems a bit muted. Not sure I am recommending anything specific here.

No action.

>     * The front page (when you click on HuBMAP on the top row) counts and plots need to be fixed before release.

When the datasets are public, the numbers will be something other than 0. No code changes required.

>     * Currently there is no benefit in having three separate top-level links: Donor/Sample/Dataset. IF there is a plan to put up more detailed information about the donors (similarly for others) than what the columns currently contain. Otherwise it just looks like too many clicks bringing you to the same spot!

Other users have found it more natural to start with Donors, and navigate down to Datasets, and it's on the roadmap to add more facets to support that.

>     * Does it make sense to wait to show donors/samples and just add more columns and only have datasets for the 1st release? BUT, if you have access to more metadata for the donors/samples currently i.e., can show more information in the tables then retain it.

Sample metadata is available and is on the roadmap to be shown as part of results.

>     * It is unclear what collections means … I can guess … but it does not immediately make sense what I am supposed to do with it. Again, think about using a collection ID to filter datasets instead of an entirely separate link up top.

When collections are in elastic search, the UI will be more consistent. https://github.com/hubmapconsortium/search-api/issues/54

>     * I think the showcases are nice, but need a LOT more in terms of description of what I am seeing and what a user could expect a few months from now with these.

Spraggins and Satija are both expects to submit their summary text soon.

>     * CCF: Why is this not a showcase?
>     * I cannot tell if it is functional currently. What exactly is it supposed to enable the user to accomplish right now?
>     * I also cannot readily tell what I am supposed to do with it. After some patience, I notice that I can click on the individually highlighted parts of the organ. So I presume I might be able to visually extract out e.g., samples that are close to the main artery and samples that are far away from the main artery of the organ. Now, something like this might be useful, BUT I really can’t tell based on the lack of contrast which areas these might be.
>     * The organs are NOT in the plane of the human.
>     * The ontology terms search box does not seem to do anything specific.
>     * It is unclear why clicking on some dataset on the right takes me to the sample page, and on others it takes me to some image and on yet others it goes nowhere. What is the image supposed to tell me?
>     * The size of the organs are not relatively scaled (I know they are roughly the same size but it might make sense to scale the size of the spleen down a little bit, it’s about 20% smaller).
>     * Is the tissue block size representative of its true size relative to the size of the organ? Clicking on the section of the tissue block, does change what is on the top … but it might be useful IF visually the change in the list on the right is enhanced in some manner by e.g., graying out or something.
>     * It might be useful to consider using a table (like in the other parts) where I could do male/female selections of samples with or without ‘close-to/far-away-from main artery’. What other utility are you imagining currently of this?

I think this is all CCF feedback which Katy has received.

**Comment by mccalluc** [comment] 2020-07-10 21:10
>     * Need more metadata in the tables that what is contained.

Guessing he means sample metadata. Will put on UI meeting agenda.

>     * Does it make sense to sorting (in lieu of some filters)?
>     * ID should be called Donor ID.
>     * Group name can be abbreviated.

Will put on [meeting agenda](https://docs.google.com/document/d/1J8k9YDyUKUr1MeDnHB52gVfMhqe_yo8O21dipjpxaUU/edit#bookmark=id.q5ns1rf555xk)

>     * Why are there links to each entity which takes me to the same place … this is confusing and irritating (when I see a link I have some baseline expectation that I will get different/relevant information … please have only one link).

Duplicate of #701

>     * What is the interpretation of ‘last modified’? Why is this useful?

on agenda.

>     * Clicking on an ID and then the protocols: does NOT take me to donor protocols aka any information about how the surgery or something like that was performed. This needs fixing.

Asked PK for clarification: Seems to be working on the one sample I looked at: [portal](https://portal.test.hubmapconsortium.org/browse/donor/dd258063b8389612a9596af734143906#protocols) --> [pipeline](https://www.protocols.io/view/vu-biomolecular-multimodal-imaging-center-biomic-k-7hhhj36?step=1) --> [sample collection](https://www.protocols.io/view/collection-and-post-surgical-excision-of-human-kid-7gehjte) 

>     * Clicking on the donor: HBM737.MBKD.598 protocol takes me to a page that says ‘There is a newer version of protocols available’ this needs to be fixed. Though I like the protocol organization provided by Vanderbilt. The other groups need to be encouraged to have individual protocols like this one: https://www.protocols.io/view/vu-biomolecular-multimodal-imaging-center-biomic-k-bfskjncw

Data problem? Messaged PK.

>     * There needs to be some marker if the protocols change between two or more donors or it hasn’t. Otherwise the user is left to click on a complicated series of protocols to find out if there is any difference at all or not.

UI Meeting agenda.

>     * HBM528.WJLC.564 donor has no information in the protocols or any other details. This seems to be true for BOTH Caltech and Stanford samples. This is URGENT.

Messaged PK.

>     * I am worried about the ‘Creator’ filter. It is unclear what it means. I also see people’s emails in Attribution. I think we need to be a bit careful about this. Do these people want their emails advertised? The contact PI is the only email contact we should retain. AND there should be multiple different types of attribution not just one name.

>     * There is something wrong with the filter arithmetic …
>     * Clicking on donors shows: 19 males, 16 females (I presume the rest of the 14 have no gender data). I also notice out of the 35, 27 are white and 8 black.
>     * But, if I select females, I see 15 while and 1 black on the filters but the table shows no blacks.
>     * I select males, I see 12 white and 7 black and the table shows 7 black (a table sorting function would be very useful to check these sort of things more readily).

Discussed this morning: When the metadata is complete these numbers will add up.

**Comment by mccalluc** [comment] 2020-07-10 21:13
Pulled out all the details: Things are on agendas or in issues, and a couple that confused me have been slacked to Peter.

**Closed by mccalluc** 2020-07-10 21:13 UTC
Labels: Alpha, UI, triage

**Comment by mccalluc** [comment] 2020-07-13 18:56
Some sub issues filed: #753, #756.
