### ISSUE TITLE
Caltech datasets missing provenance

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#797] opened 2020-07-15 21:03 UTC
## Feedback

__Help Desk Issue Tracker URL__:

__Message__:

- There is an organ (spleen) with no provenance: HBM278.KVFF.836. 

- Should the Caltech TMC be attributed with the heart organ: HBM393.MQZW.699?

- Expected sci-ATAC HBM666.FFFW.363

**Comment by pecan88** [comment] 2020-07-15 21:03
Reference ticket: https://on.spiceworks.com/tickets/open/614/activity

**Comment by mccalluc** [comment] 2020-07-17 15:34
> There is an organ (spleen) with no provenance: HBM278.KVFF.836.

https://portal.hubmapconsortium.org/browse/sample/d8204a70984bab4669121de9b9388e1d#provenance - UI makes it clear that the spleen came from a 44yo Black male. Unable to reproduce problem

> Should the Caltech TMC be attributed with the heart organ: HBM393.MQZW.699?

https://portal.hubmapconsortium.org/browse/sample/14e44841842d639b28bfdf9188a95a86 - "California Institute of Technology TMC" - Attribution is there?

> Expected sci-ATAC HBM666.FFFW.363

https://portal.hubmapconsortium.org/browse/dataset/d926c41ac08f3c2ba5e61eec83e90b0c - "sciATACseq"

@pecan88 : I can't reproduce any of these issues. Can you reach out to the user and see if these links help? I'm not sure if there was a database problem when when were looking at it, if they couldn't find the information on the screen, or something else...

**Comment by nicopierson** [comment] 2020-07-17 17:29
> There is an organ (spleen) with no provenance: HBM278.KVFF.836.
In this case, there are no samples associated to it. Otherwise not an issue.

> Should the Caltech TMC be attributed with the heart organ: HBM393.MQZW.699?
Yes, it should. Other tissues may be attributed with a different TMC, but this is not an issue for the portal.

> Expected sci-ATAC HBM666.FFFW.363
My apologies as this is a comment confirming that the dataset is up on the portal.

**Comment by mccalluc** [comment] 2020-07-18 01:30
>>  There is an organ (spleen) with no provenance: HBM278.KVFF.836
>
> In this case, there are no samples associated to it. Otherwise not an issue.

Got it: I've been thinking of provenance as where something comes from, rather than where it goes to. We do have some samples without derived datasets... Might change things to not show them by default.

> >  Should the Caltech TMC be attributed with the heart organ: HBM393.MQZW.699?
>
> Yes, it should. Other tissues may be attributed with a different TMC, but this is not an issue for the portal.

Still confused: It *is* being attributed to "California Institute of Technology TMC"... Is your point that it should just be "Caltech TMC"? Will reply on email.

**Comment by nicopierson** [comment] 2020-07-22 16:35
> Still confused: It is being attributed to "California Institute of Technology TMC"... Is your point that it should just be "Caltech TMC"? Will reply on email.

No, it is correct. My point was that other California Institute of Technology TMC datasets are derived from Stanford TMC tissue samples, which doesn't match. I talked to Yiing who collects tissues for both TMCs from the same donor, but he has stated he can only attribute the donor as one UUID. I've heard that the issue will be revisited after the first release.

**Comment by pecan88** [comment] 2020-07-24 12:34
Nico is correct - the system intentionally focuses on a single parent in order to maintain effective provenance.  Yiing is also correct - we'll talk more about it after the first data release.

**Comment by ngehlenborg** [comment] 2020-07-28 18:58
@pecan88 @mccalluc Can we close this issue? Is there anything for the TC-HMS team to do?

**Comment by mccalluc** [comment] 2020-11-13 16:58
@pecan88 : My sense from 

> I talked to Yiing who collects tissues for both TMCs from the same donor, but he has stated he can only attribute the donor as one UUID. I've heard that the issue will be revisited after the first release.

is that he thought separate TMCs should get separate Donor instances, and that's just not how it works: The Donor record reflects the actual-real-world person, and we don't clone it for each TMC.

If any more discussion is necessary, suggest making an agenda item referencing this.

**Closed by mccalluc** 2020-11-13 16:58 UTC
Labels: Alpha, UI

**Comment by pecan88** [comment] 2020-11-13 19:20
@mccalluc - yes - I agree w/ your interpretation.
