### ISSUE TITLE
Cells: Error expanding results row: `POST failed: /cells/cells-in-dataset-clusters.json`

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/portal-ui#2833] opened 2022-08-11 18:50 UTC
Querying `Gene: ACE2 | Expression Level 10<sup>-3</sup> | 1% Cell Percentage` and expanding the second result and in the browser console I see: 
```
Uncaught (in promise) Error: POST failed: /cells/cells-in-dataset-clusters.json?uuid=53cc1f9c21907d8f7880eed6828ba8a1&cell_variable_name=ACE2&min_expression=0.001
```

Commandline reproducer:
```
curl 'http://localhost:5001/cells/cells-in-dataset-clusters.json?uuid=53cc1f9c21907d8f7880eed6828ba8a1&cell_variable_name=ACE2&min_expression=0.001' -X POST
...
  File "/.../portal-ui/context/app/routes_cells.py", line 373, in cells_in_dataset_clusters
    cells=_get_cluster_cells(cells=cells_list,
  File "/.../portal-ui/context/app/routes_cells.py", line 49, in timed
    result = f(*args, **kwargs)
  File "/.../portal-ui/context/app/routes_cells.py", line 188, in _get_cluster_cells
    cell['values'][cell_variable_name] >= min_expression,
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
```

**Comment by SFD5311** [comment] 2022-08-11 19:05
Preliminary investigation shows one cell in each of two ATAC-seq datasets that return None when their expression values are queried for.  This should be remedied with the new ATAC-seq index version, but I will do some additional investigation to try and find a root cause.

**Comment by mccalluc** [comment] 2022-08-19 13:50
Update:
> Still thinking that the ATAC-seq index I'm finishing up testing on now will fix this.  Still don't have the clearest idea of how it happened in the first place, but adding data checks to application startup is high on my to-do list and will avoid such things in the future.

**Comment by john-conroy** [comment] 2022-09-23 20:26
Closing. From @SFD5311 

> I'd say that issue can be closed.  That dataset is now rendering properly.  The startup-time data integrity checks to catch similar errors in the future are still in progress.  I did notice a bug in the ATAC dataset queries while I was confirming, which I'm in the process of fixing/deploying right now.  It just requires an adjustment of a data file, no new code.

**Closed by john-conroy** 2022-09-23 20:26 UTC
Labels: bug, feature: cells
