### ISSUE TITLE
Searching by specific HBM ID returns multiple pages of results

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#2520] opened 2022-03-22 16:44 UTC
When I go to the portal, search for a specific donor based on its HuBMAP ID (HBM.xxx.xxxx.xxx), I cannot easily tell which result is the correct dataset I searched for by ID.

For example, when I search for HBM874.HRDG.774 (UCSD dataset) there are 3 pages of results and it requires manually scanning the IDs to try to find the dataset.  I would expect that when given a precise HuBMAP ID, the search would return said dataset alone, or worst case if it also included derived / parent datasets for that ID.

This bug comes from JCS and Peter verified.

**Comment by mccalluc** [comment] 2022-03-22 18:19
- Duplicate of https://github.com/hubmapconsortium/search-api/issues/328
- Alternative approach: https://github.com/hubmapconsortium/portal-ui/issues/844

Closing.

The string is tokenized and split on periods, and a match on any portion ("HBM874" or "HRDG" or "774") counts as a match for the document.

**Comment by pecan88** [comment] 2022-03-23 10:38
Matching on any portion is unhelpful when you enter a complete ID string.  Would it not be better to match to complete string?  Even if it is displayed as the first value on the list, that would go a long way to helping usability & expected behavior.

**Comment by mccalluc** [comment] 2022-03-23 14:23
@pecan88 -- Is there something here that is different from the linked duplicate issue?

**Comment by mccalluc** [comment] 2022-03-24 20:44
Filed several new issues in this space, and the original [duplicate issue](https://github.com/hubmapconsortium/search-api/issues/328) is still there. If there is something precise that none of these address, please clarify.
- #2530 
- #2531 
- #2532

**Closed by mccalluc** 2022-03-24 20:44 UTC
Labels: bug
