### ISSUE TITLE
Counts on main Portal page show nothing

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/portal-ui#691] opened 2020-07-09 19:50 UTC
I think this is known although my assumption is that Ajay is logged in.

**Relevant email section:** * The front page (when you click on HuBMAP on the top row) counts and plots need to be fixed before release. 

Entire Email: 
Some top-level comments:
* I like the overall design, though it seems a bit muted. Not sure I am recommending anything specific here. 
* The front page (when you click on HuBMAP on the top row) counts and plots need to be fixed before release. 
* Currently there is no benefit in having three separate top-level links: Donor/Sample/Dataset. IF there is a plan to put up more detailed information about the donors (similarly for others) than what the columns currently contain. Otherwise it just looks like too many clicks bringing you to the same spot! 
* Does it make sense to wait to show donors/samples and just add more columns and only have datasets for the 1st release? BUT, if you have access to more metadata for the donors/samples currently i.e., can show more information in the tables then retain it. 
* It is unclear what collections means … I can guess … but it does not immediately make sense what I am supposed to do with it. Again, think about using a collection ID to filter datasets instead of an entirely separate link up top. 
* I think the showcases are nice, but need a LOT more in terms of description of what I am seeing and what a user could expect a few months from now with these. 
* CCF: Why is this not a showcase? 
* I cannot tell if it is functional currently. What exactly is it supposed to enable the user to accomplish right now? 
* I also cannot readily tell what I am supposed to do with it. After some patience, I notice that I can click on the individually highlighted parts of the organ. So I presume I might be able to visually extract out e.g., samples that are close to the main artery and samples that are far away from the main artery of the organ. Now, something like this might be useful, BUT I really can’t tell based on the lack of contrast which areas these might be. 
* The organs are NOT in the plane of the human. 
* The ontology terms search box does not seem to do anything specific. 
* It is unclear why clicking on some dataset on the right takes me to the sample page, and on others it takes me to some image and on yet others it goes nowhere. What is the image supposed to tell me? 
* The size of the organs are not relatively scaled (I know they are roughly the same size but it might make sense to scale the size of the spleen down a little bit, it’s about 20% smaller). 
* Is the tissue block size representative of its true size relative to the size of the organ? Clicking on the section of the tissue block, does change what is on the top … but it might be useful IF visually the change in the list on the right is enhanced in some manner by e.g., graying out or something. 
* It might be useful to consider using a table (like in the other parts) where I could do male/female selections of samples with or without ‘close-to/far-away-from main artery’. What other utility are you imagining currently of this?
---ajay 
PS: I expect to send a few more emails with more specific feedback.

**Comment by mccalluc** [comment] 2020-07-10 20:44
Duplicate of #693. Closing.

**Closed by mccalluc** 2020-07-10 20:44 UTC
Labels: Alpha, UI, bug
