### ISSUE TITLE
Broken image link in Documentation > APIs

### ISSUE THREAD

**Issue by admin-hubmapconsortium** [hubmapconsortium/portal-ui#1163] opened 2020-09-01 20:42 UTC
Image is not coming through on the API documentation page. (Browser = Chrome, current version)

![image001](https://user-images.githubusercontent.com/70603634/91903942-11f64300-ec72-11ea-9070-2bbd6dc84888.jpg)

**Comment by mccalluc** [comment] 2020-09-01 20:49
Duplicate of https://github.com/hubmapconsortium/portal-docs/issues/6 . closing.

**Closed by mccalluc** 2020-09-01 20:49 UTC
Labels: UI, bug
